### PR TITLE
Task 6 - Add integration with SQS & SNS

### PR DESCRIPTION
**Pull request by AndrewShamrey**
What was done?
 - `catalogBatchProcess` Lambda was created
 - `catalogItemsQueue` Queue was created
 - `createProductTopic` Topic was created 
 - All resources was configured correctly 

Additional: 
- Unit tests for `catalogBatchProcess` lambda
- Second Subscription filtered by product.count

Links:
- [Product API](https://lrznfwuq7h.execute-api.eu-north-1.amazonaws.com)
- [Import API](https://n3pn2plh42.execute-api.eu-north-1.amazonaws.com/prod/)
- [Frontend](https://d1qhaa2cut6jyu.cloudfront.net/)

Please use correct format of csv file (see image below for example)
Снимок экрана 2023-06-27 в 01 03 02

 Self-check score - __100__

### CODE REVIEW

**Comment by BusyginArtem** [comment]
I've tried to upload some products, but I didn't successed.

**Comment by AndrewShamrey** [comment]
@BusyginArtem  Please check it again. I see that everything is working correctly. Please recheck the data format.

**Comment by BusyginArtem** [comment]
Could you attach a .csv file with the correct column separator. I've used the comma and semicolon separators.

**Comment by AndrewShamrey** [comment]
@BusyginArtem 
I have already attached a screenshot showing the structure of the file. I will assume that you write product data separated by commas in one cell. Also, please note that the first line must be the names of the fields
An example file can be downloaded from the link: [newproductsfile.csv](https://github.com/AndrewShamrey/nodejs-aws-shop-backend/files/11899176/newproductsfile.csv)

**Comment by AndrewShamrey** [comment]
@BusyginArtem Please recheck my task with correct data

**Pull request merged**
